# Generated by Django 6.0.5 on 2026-10-02 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_addresszone_options_and_more'),
        ('organizations', '0001_initial'),
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smsgateway',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_gateways', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['organization', 'created_at'], name='smslog_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['organization', 'status'], name='smslog_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='smsgateway',
            constraint=models.UniqueConstraint(fields=('organization', 'label'), name='unique_sms_gateway_label_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='smstemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_sms_template_name_per_organization'),
        ),
    ]
