# Generated by Django 6.0.5 on 2026-10-02 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('sms', '0002_smsgateway_organization_smslog_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsgateway',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_gateways', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='organizations.organization'),
        ),
    ]
