# Generated by Django 6.0.5 on 2026-10-01 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_paymenttransaction_payment_method'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='organizations.organization'),
        ),
    ]
