# Generated by Django 6.0.5 on 2026-10-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_package_organization'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_package_name_per_organization'),
        ),
    ]
