# Generated by Django 6.0.5 on 2026-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_package_name_alter_package_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash Payment'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('adjustment', 'Manual Adjustment'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
