# Generated by Django 6.0.5 on 2026-10-09 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_paymenttransaction_payment_method'),
        ('customers', '0009_alter_addresszone_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_method', 'mpesa'), ('transaction_id__isnull', False), models.Q(('transaction_id', ''), _negated=True)), fields=('transaction_id',), name='unique_mpesa_transaction_id'),
        ),
    ]
