# Generated by Django 6.0.5 on 2026-10-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_addresszone_options_and_more'),
        ('olt', '0004_alter_oltdevice_olt_type'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onu',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olt_devices', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='oltdevice',
            constraint=models.UniqueConstraint(fields=('organization', 'host', 'telnet_port'), name='unique_olt_endpoint_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='onu',
            constraint=models.UniqueConstraint(fields=('olt', 'onu_index'), name='unique_onu_index_per_olt'),
        ),
    ]
