# Generated by Django 6.0.5 on 2026-10-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0005_alter_onu_unique_together_oltdevice_organization_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltdevice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olt_devices', to='organizations.organization'),
        ),
    ]
