# Generated by Django 6.0.5 on 2026-10-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_package_name_alter_package_organization_and_more'),
        ('customers', '0008_addresszone_organization_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresszone',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['customer_id']},
        ),
        migrations.AlterField(
            model_name='addresszone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='addresszone',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_zone_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'customer_id'), name='unique_customer_id_per_organization'),
        ),
    ]
