# Generated by Django 6.0.5 on 2026-10-08 13:51

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0008_alter_package_name_alter_package_organization_and_more'),
        ('customers', '0009_alter_addresszone_options_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(choices=[('own_shortcode', 'ISP-Owned Shortcode'), ('lintech_managed', 'Lintech Managed')], default='own_shortcode', max_length=30)),
                ('service_scope', models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot'), ('both', 'PPPoE and Hotspot')], default='pppoe', max_length=20)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('transaction_type', models.CharField(choices=[('paybill', 'PayBill'), ('till', 'Till / Buy Goods')], default='paybill', max_length=20)),
                ('shortcode', models.CharField(blank=True, default='', max_length=20)),
                ('consumer_key', core.fields.EncryptedTextField(blank=True, default='')),
                ('consumer_secret', core.fields.EncryptedTextField(blank=True, default='')),
                ('passkey', core.fields.EncryptedTextField(blank=True, default='')),
                ('callback_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_mpesa_integrations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_configurations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'M-Pesa Configuration',
                'verbose_name_plural': 'M-Pesa Configurations',
                'ordering': ['organization_id', 'service_scope', '-is_default'],
            },
        ),
        migrations.CreateModel(
            name='C2BTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trans_id', models.CharField(max_length=50)),
                ('bill_ref_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('business_shortcode', models.CharField(blank=True, default='', max_length=20)),
                ('allocation_status', models.CharField(choices=[('unallocated', 'Unallocated'), ('matched', 'Matched'), ('manually_allocated', 'Manually Allocated'), ('rejected', 'Rejected')], default='unallocated', max_length=30)),
                ('raw_payload', core.fields.EncryptedJSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2b_transactions', to='customers.customerprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2b_transactions', to='organizations.organization')),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c2b_transaction', to='billing.paymenttransaction')),
                ('payment_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='c2b_transactions', to='payments.mpesaconfiguration')),
            ],
            options={
                'verbose_name': 'M-Pesa C2B Transaction',
                'verbose_name_plural': 'M-Pesa C2B Transactions',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('hotspot', 'Hotspot')], max_length=20)),
                ('purpose', models.CharField(choices=[('pppoe_renewal', 'PPPoE Renewal'), ('pppoe_plan_change', 'PPPoE Plan Change'), ('hotspot_purchase', 'Hotspot Purchase'), ('connection_fee', 'Connection Fee'), ('invoice_payment', 'Invoice Payment'), ('account_topup', 'Account Top-up')], max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_reference', models.CharField(blank=True, default='', max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('settlement_status', models.CharField(choices=[('unsettled', 'Unsettled'), ('settling', 'Settling'), ('settled', 'Settled'), ('settlement_failed', 'Settlement Failed')], default='unsettled', max_length=30)),
                ('provisioning_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('provisioned', 'Provisioned'), ('failed', 'Failed')], default='not_required', max_length=20)),
                ('result_code', models.CharField(blank=True, default='', max_length=20)),
                ('result_description', models.TextField(blank=True, default='')),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('callback_payload', core.fields.EncryptedJSONField(blank=True, default=dict)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('connection_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payment_attempts', to='billing.connectionfee')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payment_attempts', to='customers.customerprofile')),
                ('monthly_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payment_attempts', to='billing.monthlybill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='organizations.organization')),
                ('payment_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='payments.mpesaconfiguration')),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_attempt', to='billing.paymenttransaction')),
                ('target_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payment_attempts', to='billing.package')),
            ],
            options={
                'verbose_name': 'M-Pesa Payment Attempt',
                'verbose_name_plural': 'M-Pesa Payment Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mpesaconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('organization', 'service_scope'), name='unique_active_default_mpesa_config_per_scope'),
        ),
        migrations.AddIndex(
            model_name='c2btransaction',
            index=models.Index(fields=['organization', 'allocation_status', 'received_at'], name='c2b_org_alloc_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='c2btransaction',
            constraint=models.UniqueConstraint(fields=('payment_configuration', 'trans_id'), name='unique_c2b_trans_per_config'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='mpesa_attempt_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['settlement_status', 'created_at'], name='mpesa_attempt_settle_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provisioning_status', 'created_at'], name='mpesa_attempt_prov_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_receipt_number__isnull', False)), fields=('payment_configuration', 'mpesa_receipt_number'), name='unique_mpesa_receipt_per_config'),
        ),
    ]
