# Generated by Django 6.0.5 on 2026-10-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0001_initial'),
        ('customers', '0009_alter_addresszone_options_and_more'),
        ('mikrotik', '0004_alter_mikrotikrouter_options_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandwidthsample',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_samples', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='bandwidthsample',
            index=models.Index(fields=['organization', 'created_at'], name='bandwidth_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bandwidthsample',
            index=models.Index(fields=['organization', 'pppoe_id'], name='bandwidth_org_pppoe_idx'),
        ),
    ]
