# Generated by Django 6.0.5 on 2026-10-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandwidth', '0002_bandwidthsample_organization_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandwidthsample',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_samples', to='organizations.organization'),
        ),
    ]
