"""add service plans

Revision ID: 27a96a2952ed
Revises: 3cbc0b0293d4
Create Date: 2026-09-28 11:29:49.153284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a96a2952ed'
down_revision = '3cbc0b0293d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('service_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('download_speed', sa.Integer(), nullable=True),
    sa.Column('upload_speed', sa.Integer(), nullable=True),
    sa.Column('data_limit', sa.Integer(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_plans_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_plans_service_type'), ['service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_plans_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_plans_status'))
        batch_op.drop_index(batch_op.f('ix_service_plans_service_type'))
        batch_op.drop_index(batch_op.f('ix_service_plans_organization_id'))

    op.drop_table('service_plans')
    # ### end Alembic commands ###
