"""scope customer phone and email uniqueness by organization

Revision ID: 3cbc0b0293d4
Revises: a014746e62a0
Create Date: 2026-09-26 04:40:39.088790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbc0b0293d4'
down_revision = 'a014746e62a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)
        batch_op.create_unique_constraint('uq_customer_organization_email', ['organization_id', 'email'])
        batch_op.create_unique_constraint('uq_customer_organization_phone', ['organization_id', 'phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customer_organization_phone', type_='unique')
        batch_op.drop_constraint('uq_customer_organization_email', type_='unique')
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=True)
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=True)

    # ### end Alembic commands ###
