# Generated by Django 6.0.5 on 2026-10-01 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0002_routerinfo_profile_name'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikrotikrouter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mikrotik_routers', to='organizations.organization'),
        ),
    ]
