# Generated by Django 6.0.5 on 2026-10-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0003_mikrotikrouter_organization'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mikrotikrouter',
            options={'ordering': ['name'], 'verbose_name': 'MikroTik Router', 'verbose_name_plural': 'MikroTik Routers'},
        ),
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mikrotik_routers', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='mikrotikrouter',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_router_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='mikrotikrouter',
            constraint=models.UniqueConstraint(fields=('organization', 'host', 'port'), name='unique_router_endpoint_per_organization'),
        ),
    ]
