# Generated by Django 6.0.5 on 2026-10-07 14:59

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0004_alter_mikrotikrouter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotikrouter',
            name='password',
            field=core.fields.EncryptedTextField(help_text='Router API password'),
        ),
        migrations.AlterField(
            model_name='routerinfo',
            name='pppoe_pass',
            field=core.fields.EncryptedTextField(),
        ),
    ]
